version: "3.8"

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim    
    container_name: oracle_db
    ports:
      - "1521:1521"       # port no on the machine (host machine) : port no inside the container (container's services)
    environment:
      ORACLE_PASSWORD: adminpassword
      ORACLE_DATABASE: XEPDB1 
      APP_USER: system
      APP_USER_PASSWORD: adminpassword
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
